### ISSUE TITLE
Add prettier and linting

### ISSUE THREAD

**Issue by rolznz** [getAlby/js-lightning-tools#45]
It would be nice to add prettier and pre-commit linting (using husky). This way later commits do not keep changing the formatting.

Maybe the extension can be looked at as an example.

**Comment by abhiShandy** [comment]
Do you want to use something like browser extension [package.json](https://github.com/getAlby/lightning-browser-extension/blob/master/package.json)?

**Comment by rolznz** [comment]
@pavanjoshi914 worked on this. Thanks!
