### ISSUE TITLE
Implement a requestPayment function with webln + fallback

### ISSUE THREAD

**Issue by bumi** [getAlby/js-lightning-tools#5]
a generic `requestPayment(invoice)` function that checks if webln is available, and if so it calls webln. 
otherwise it renders a DOM element with a QR code + an input field to copy the invoice.

**Comment by rolznz** [comment]
@bumi is this solved by https://github.com/getAlby/bitcoin-connect ?

**Comment by rolznz** [comment]
fixed by bitcoin connect
