### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by czloviczek** [getAlby/js-lightning-tools#58]
Please, help me to handle this error: 
Uncaught SyntaxError: Cannot use import statement outside a module 

happening for line:   
import { LightningAddress } from "@getalby/lightning-tools";

My code is just the example:

<html>
<head>
// lightning-tools now available at window.lightningTools
<script  type="module" src="https://cdn.jsdelivr.net/npm/@getalby/lightning-tools@latest/dist/index.browser.js"></script>
</head>
<body>
<script>
   
   import { LightningAddress } from "@getalby/lightning-tools";

const ln = new LightningAddress("hello@getalby.com");

// fetch the LNURL data
await ln.fetch();

// get the LNURL-pay data:
console.log(ln.lnurlpData); // returns a [LNURLPayResponse](https://github.com/getAlby/js-lightning-tools/blob/master/src/types.ts#L1-L15)
// get the keysend data:
console.log(ln.keysendData);
</script>
</body>
</html>

**Comment by bumi** [comment]
when you do the <script src from jsdelivr you do NOT need to `import { LightningAddress }`

just do 

```
<script src="https://cdn.jsdelivr.net/npm/@getalby/lightning-tools@latest/dist/index.browser.js"></script>
<script>
  const ln = window.lightningTools.LightningAddress("michael@getalby.com"));
  ///...
</script>
```

**Comment by czloviczek** [comment]
Thanks @bumi for a prompt answer, but this did not help. Now receiving:

Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules

**Comment by bumi** [comment]
await can only be used in async functions.

e.g.
```
async function main() {
  const ln = window.lightningTools.LightningAddress("michael@getalby.com"));
  await ln.fetch();
  const invoice = await ln.requestInvoice({satoshi: 1000});
}

main();
```

or use `.then()`

```
const ln = window.lightningTools.LightningAddress("michael@getalby.com"));
ln.fetch().then(() => {
  ...
});

**Comment by rolznz** [comment]
We have updated the example in the README to use Javascript modules. Please try again and if you still have issues please open a new issue. Thanks!
